mode: deployment
config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
  exporters:
    logging:
      loglevel: info
    jaeger:
      endpoint: simplest-collector:14250
      tls:
        insecure: true
  extensions:
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679
  processors:
    batch:
      timeout: 1s
    resource:
      attributes:
        - key: test.key
          value: "test-value"
          action: insert
  service:
    extensions: [pprof, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, resource]
        exporters: [logging, jaeger]